spring.application.name=order-service-webshop
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}
app.auth-server-url=${AUTH_SERVER_URL:http://localhost:9000}
spring.jpa.hibernate.ddl-auto=update


